version: "3"

volumes:
  db:
    driver: local
# TODO: Database config should be:
# - "postgres" - "-c" "-config-file=/etc/postgresql/postgresql.conf"
# With volume on Docker.

services:
  database:
    image: postgres:14-alpine
    hostname: kirillzhosul-api
    restart: always
    volumes:
      - ../db:/var/lib/postgresql/data
    env_file:
      - .database.env
    networks:
      - kirillzhosul-api
    command:
      - "postgres"
      - "-c" # Max connection limit for database.
      - "max_connections=1000" # SHOW max_connections;
      - "-c" # Buffer size for database bufferization.
      - "shared_buffers=128MB" # SHOW shared_buffers;
  database-poller:
    image: edoburu/pgbouncer
    env_file:
      - .database.env
    depends_on:
      - database
    networks:
      - kirillzhosul-api
  cache:
    image: redis:7-alpine
    hostname: kirillzhosul-api
    restart: always
    command: redis-server
    volumes:
      - ../cache:/data
    networks:
      - kirillzhosul-api
  server:
    hostname: kirillzhosul-api
    restart: always
    env_file:
      - .server.env
    volumes:
      - ./api:/srv/www/kirillzhosul/api
    ports:
      - "${COMPOSE_EXPOSED_PORT}:80"
    depends_on:
      - database
      - database-poller
      - cache
    links:
      - database
      - cache
    networks:
      - kirillzhosul-api
    build: .

networks:
  kirillzhosul-api:
